# Generated by Django 2.1.5 on 2020-12-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=150)),
                ('opis', models.TextField()),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('zrealizowany', models.BooleanField(default=False)),
            ],
        ),
    ]
